### ISSUE TITLE
aiohttp connection error 

### ISSUE THREAD

**Issue by mdnaimul22** [enarjord/passivbot_binance_isolated_margin_legacy#14]
python3.9 passivbot_isolated_margin.py default        user default                                            2021-07-06T14:45:40  initiating ema MATIC/BTC
2021-07-06T14:45:41  updating all balances              2021-07-06T14:45:41  dumping balance log                2021-07-06T14:45:42  updating borrowable MATIC/BTC MATIC                                                        2021-07-06T14:45:42  updating borrowable MATIC/BTC BTC  2021-07-06T14:45:43  updating my trades MATIC/BTC
error with fetch_my_trades unsupported operand type(s) for /: 'str' and 'int' Traceback (most recent call last):  File "/data/data/com.termux/files/home/passivbot/passivbot_isolated_margin.py", line 42, in tw
    return await fn(*args, **kwargs)                      File "/data/data/com.termux/files/home/passivbot/passivbot_isolated_margin.py", line 637, in fetch_my_trades      print_(['fetched my trades', symbol, ts_to_date(my_trades[0]['time'] / 1000)])                              TypeError: unsupported operand type(s) for /: 'str' and 'int'
 ('MATIC/BTC',) {}                                      Traceback (most recent call last):                        File "/data/data/com.termux/files/home/passivbot/passivbot_isolated_margin.py", line 1532, in <module>            asyncio.run(main())
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/runners.py", line 44, in run                          return loop.run_until_complete(main)                  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete      return future.result()
  File "/data/data/com.termux/files/home/passivbot/passivbot_isolated_margin.py", line 1523, in main                bot = await create_bot(settings)
  File "/data/data/com.termux/files/home/passivbot/passivbot_isolated_margin.py", line 51, in create_bot
    await bot._init()                                     File "/data/data/com.termux/files/home/passivbot/passivbot_isolated_margin.py", line 174, in _init
    await asyncio.gather(*[self.update_my_trades(s) for s in self.symbols])                                       File "/data/data/com.termux/files/home/passivbot/passivbot_isolated_margin.py", line 687, in update_my_trades     self.last_my_trades_id[symbol] = mts[-1]['id'] if mts else 0
TypeError: 'TypeError' object is not subscriptable
binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).                   Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x79913de5b0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x79913ea0a0>, 158528.254142493), (<aiohttp.client_proto.ResponseHandler object at 0x798e98e760>, 158529.045010358)]']                                         connector: <aiohttp.connector.TCPConnector object at 0x7991468fd0>

**Comment by guntoken** [comment]
same issue here. anybody can help us, please? many thanks in advance
