### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'float' binance requires to release all resources with an explicit call to the .close() coroutine. 

### ISSUE THREAD

**Issue by guntoken** [enarjord/passivbot_binance_isolated_margin_legacy#16]
here's my error:"Traceback (most recent call last):
  File "/Users/passivbot_binance_isolated_margin_legacy/passivbot_isolated_margin.py", line 1532, in <module>
    asyncio.run(main())
  File "/Users/.pyenv/versions/3.10.12/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/.pyenv/versions/3.10.12/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/passivbot_binance_isolated_margin_legacy/passivbot_isolated_margin.py", line 1523, in main
    bot = await create_bot(settings)
  File "/Users/passivbot_binance_isolated_margin_legacy/passivbot_isolated_margin.py", line 51, in create_bot
    await bot._init()
  File "/Users/passivbot_binance_isolated_margin_legacy/passivbot_isolated_margin.py", line 144, in _init
    self.last_price = {s_: tickers[s_]['last'] for s_ in tickers if tickers[s_]['last'] > 0.0}
  File "/Users/passivbot_binance_isolated_margin_legacy/passivbot_isolated_margin.py", line 144, in <dictcomp>
    self.last_price = {s_: tickers[s_]['last'] for s_ in tickers if tickers[s_]['last'] > 0.0}
TypeError: '>' not supported between instances of 'NoneType' and 'float'
binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x117e57ac0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x117efe200>, 429629.236401458)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x122143820>, 429629.455532416)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x117efd900>, 429630.147231708)]']
connector: <aiohttp.connector.TCPConnector object at 0x117e57a90>"

**Comment by adrian96b** [comment]
i've been dealing with the exact same issue, please help
