### ISSUE TITLE
[Ask]: Trading Progress

### ISSUE THREAD

**Issue by thorjeus** [enarjord/passivbot_binance_isolated_margin_legacy#9]
Hi,

I tried this few hours ago with one coin at the config and found this in terminal:

2020-09-21T05:55:51  initiating ema IOTA/BTC 
2020-09-21T05:55:51  updating all balances 
2020-09-21T05:55:52  dumping balance log 
2020-09-21T05:55:52  finished init 
2020-09-21T05:55:52  {} 
2020-09-21T05:55:52  wss://stream.binance.com:9443/stream?streams= 
2020-09-21T05:55:52  longing [] 
2020-09-21T05:55:52  shrting []

IOTA/BTC BTC 'max_leverage'
Traceback (most recent call last):
  File "passivbot_isolated_margin.py", line 414, in update_borrowable
    (self.settings[symbol]['max_leverage'] - 1) -
KeyError: 'max_leverage'

2020-09-21T06:30:08  updating my trades IOTA/BTC 
2020-09-21T06:30:08  updating open_orders IOTA/BTC 
2020-09-21T06:30:08  finished init 
2020-09-21T06:30:08  {'iotabtc@depth5': 'IOTA/BTC'} 
2020-09-21T06:30:08  wss://stream.binance.com:9443/stream?streams=iotabtc@depth5 
2020-09-21T06:30:08  longing ['IOTA/BTC'] 
2020-09-21T06:30:08  shrting ['IOTA/BTC'] 
error with execute_to_exchange 'min_markup_pct' Traceback (most recent call last):
  File "passivbot_isolated_margin.py", line 42, in tw
    return await fn(*args, **kwargs)
  File "passivbot_isolated_margin.py", line 755, in execute_to_exchange
    eligible_orders, repays = self.get_ideal_orders(s)
  File "passivbot_isolated_margin.py", line 1049, in get_ideal_orders
    self.settings[s]['min_markup_pct'],
KeyError: 'min_markup_pct'

Could you please inform that those are ok? Is it running?
Appreciate for any informations.

Thanks& Regards.

**Comment by enarjord** [comment]
hello,

thanks for your comment, it revealed an error in the program.
the default settings file belonged to an older version and was incompatible with the newest version of the bot.

it is fixed now.

thanks again.

**Comment by thorjeus** [comment]
Thanks a lot, will give it a try.
_Edited: It is working now._

Ps.
Great work.
